Repository yagyesh-bobde/GenAI-Projects, pull requests merged in 2024-01, with the labels that each got.

#57 Update index.html
  index.html
Labels: good first issue, SWOC S4, web, easy

#58 Update index.js
  AI-Text-Summarizer-App/index.js
Labels: bug, enhancement, SWOC S4, easy

#69 Updated contributors file
  CONTRIBUTORS.md
Labels: enhancement, good first issue, SWOC S4, beginner

#70 Added my idea in the ideas file
  Ideas/README.md
Labels: enhancement, SWOC S4, beginner
